server:
  port: 9006
spring:
  application:
    name: sms
  rabbitmq:
    host: 192.168.247.128
    port: 5672
    username: guest
    password: guest
sms:
  appcode: 749a0dc1c7a54749bf2e816115cecff1  #使用自己的AppCode
  tpl_id: TP1711063    # 默认模板